### PR TITLE
Temporarily removing veth_host interface and EP file - part 2

### PR DESCRIPTION
**Pull request by snaiksat**
Since we are seeing some asymmetrical routing on account
of the route to the pod network added to support the
use of the veth_host interface.

### CODE REVIEW

**Comment by jojimt** [comment]
Removing this only for on-prem, right?

**Comment by snaiksat** [comment]
@jojimt this is being done on a jordan-eft branch which is not being used for overlay, only for EFT on on-prem.

**Comment by jojimt** [comment]
oh ok

**Comment by snaiksat** [comment]
Tests need to be updated but merging this for now since we need an urgent build.

**Pull request merged**
