### PR TITLE
Cluster Report : Collect network policy

### PR DESCRIPTION
**Pull request by pkharat**

### CODE REVIEW

**Comment by pkharat** [comment]
Used script https://github.com/noironetworks/acc-pytests/blob/master/scripts/create_resources.py to create network policies.

After running 
`noiro@k8s27-ext-rtr:~/pritam/aci-containers/dist$ ./acikubectl debug cluster-report -o cluster-report.tar.gz`
verified file "status/network_policy.log" is created.

Log snippet

```
....
....
Running command: kubectl get -n aci-containers-system all -o yaml
Running command: kubectl get nodes -o=jsonpath={range.items[*]}{@.metadata.name}
{@.metadata.annotations.opflex\.cisco\.com/pod-network-ranges}
Running command: kubectl get networkpolicy --all-namespaces -o yaml
Running command: kubectl cp aci-containers-system/aci-containers-host-frcnh:/usr/local/var/lib/opflex-agent-ovs hostfiles/node-k8s27-node-2.local.lan/opflex-agent-ovs/
....
....

```

```
noiro@k8s27-ext-rtr:~/pritam/aci-containers/dist/cluster-report/status$ tree
.
├── acioperator_deployment_status.log
├── cluster-info.log
├── configmap_accprovisionoperator.log
├── configmap_acioperator.log
├── configmap_controller.log
├── configmap_snatoperator.log
├── controller_deployment_status.log
├── erspan_policy.log
├── get_aci_namespace_status.log
├── get_nodes_status.log
├── host_daemonset_status.log
├── ipam_details_all_nodes.log
├── netflow_policy.log
├── network_policy.log
├── node_info.log
├── node_podifs.log
├── ovs_daemonset_status.log
├── pods_status.log
├── qos_policy.log
├── services_status.log
├── snat_globalinfo.log
├── snat_localinfo.log
└── snat_policy.log

0 directories, 23 files

```

```
noiro@k8s27-ext-rtr:~/pritam/aci-containers/dist/cluster-report/status$ cat network_policy.log | less
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2023-07-04T11:25:35Z"
    generation: 1
    name: allow-from-ingress
    namespace: group-1-ns
    resourceVersion: "8802363"
    uid: e469e8fd-72ef-4df7-bc9f-dcefae6f6592
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    podSelector: {}
    policyTypes:
    - Ingress
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2023-07-04T11:25:35Z"
    generation: 1
    name: allow-from-openshift-monitoring
    namespace: group-1-ns
    resourceVersion: "8802367"
    uid: 2ae114a7-91fc-4603-b18c-86f24dff0d91
  spec:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: monitoring
    podSelector: {}
    policyTypes:
    - Ingress
  status: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    creationTimestamp: "2023-07-04T11:25:35Z"
    generation: 1
    name: allow-same-namespace
    namespace: group-1-ns
    resourceVersion: "8802374"
    uid: 76612750-9f3b-4680-8e08-f3636e867d48
  spec:
    ingress:
    - from:
      - podSelector: {}
    podSelector: {}
    policyTypes:
    - Ingress
  status: {}

....
....
....
....
....
```

**Comment by snaiksat** [comment]
Thanks @pkharat . How many bytes does each networkpolicy add, I am trying to get a feel for how big this new log file can get.

**Comment by snaiksat** [comment]
@pkharat , my question above ^^^

**Comment by pkharat** [comment]
> Thanks @pkharat . How many bytes does each networkpolicy add, I am trying to get a feel for how big this new log file can get.

@snaiksat netpolicies listed above are of these sizes

```
noiro@k8s27-ext-rtr:~/pritam/acc-pytests/scripts$ ls -lh netpol*
-rw-rw-r-- 1 noiro noiro 811 Jul 11 23:40 netpol-allow-from-ingress.yaml
-rw-rw-r-- 1 noiro noiro 817 Jul 11 23:42 netpol-allow-from-openshift-monitoring.yaml
-rw-rw-r-- 1 noiro noiro 671 Jul 11 23:45 netpol-allow-same-namespace.yaml
-rw-rw-r-- 1 noiro noiro 576 Jul 11 23:45 netpolc-deny-by-default.yaml

```

**Pull request merged**
