### PR TITLE
acikubectl enchancements (issue #1495):

### PR DESCRIPTION
**Pull request by anmol372**
1. Added logs from aci-containers-host (/usr/local/var/lib/aci-containers/k8s-pod-network/)
2. Added build time and commit id's:
	2.1 aci-containers-controller : cluster-report/logs/controller/acc-version.log
	2.2 aci-containers-host: cluster-report/logs/node-%s/aci-containers-host-version.log
3. Corrected output dir structure, to not produce empty hostfiles dir, and instead only produce a single hostfiles.tar

(cherry picked from commit f77997a)

### CODE REVIEW

**Comment by anmol372** [comment]
Cherry-pick for issue: https://github.com/noironetworks/support/issues/1495

**Comment by snaiksat** [comment]
This is trying to merge the same thing back into the master. The merge is into the kwai branch. You will probably have to create a new PR.

**Comment by snaiksat** [comment]
was "-x" used in the cherry-pick?

**Comment by anmol372** [comment]
> was "-x" used in the cherry-pick?

Done now, will keep in mind for future cherry-picks

**Review by apoorva11029 — APPROVED** [review]

**Comment by apoorva11029** [comment]
Thanks for fixing the cherry-pick, merging now.

**Pull request merged**
