### PR TITLE
gofmt fixes

### PR DESCRIPTION
**Pull request by amittbose**
Signed-off-by: Amit Bose <amitbose@gmail.com>

### CODE REVIEW

**Comment by readams** [comment]
How did you run this? There's a bunch of changes in there that are not how gofmt formats the code.

**Comment by amittbose** [comment]
This is the command I ran:
gofmt -tabwidth=4 -w=true <path>

**Comment by readams** [comment]
Just run with default settings no tabwidth=4

**Comment by amittbose** [comment]
Updated.

**Pull request merged**
