### PR TITLE
Commit vendor folder

### PR DESCRIPTION
**Pull request by kishorejonnala**
Bringing vendor dependency code alone into master.

### CODE REVIEW

**Comment by jojimt** [comment]
Please do not commit this separately as it is already part of the demo branch.

**Comment by kishorejonnala** [comment]
@jojimt Sumit was asking to merge these changes separately into master. Hence the PR. Lets discuss tomorrow and decide whether to merge.

**Comment by jojimt** [comment]
https://github.com/noironetworks/aci-containers/pull/281 is the PR I created incorporating those changes. I don't understand the need for parallel PRs.

**Comment by snaiksat** [comment]
I will close this PR for now to avoid unnecessary distraction and back-n-forth. We will sync up offline.

**Pull request closed without merging**
