### PR TITLE
Supporting new flavors in aci-operator for OCP-4.7

### PR DESCRIPTION
**Pull request by abhis2112**

### CODE REVIEW

**Comment by snaiksat** [comment]
Can we preemptively make the changes for the ESX flavor as well so that we don't have to do another round of PRs?

**Comment by abhis2112** [comment]
Supporting new flavors in aci-operator for OCP-4.7
    1. openshift-4.7-openstack
    2. openshift-4.6-esx
    3. openshift-4.7-esx

> Can we preemptively make the changes for the ESX flavor as well so that we don't have to do another round of PRs?

resolved

**Comment by snaiksat** [comment]
For ESX, we also need to update the following, right?

https://github.com/noironetworks/aci-containers/blob/master/pkg/hostagent/services.go#L114

**Comment by abhis2112** [comment]
> For ESX, we also need to update the following, right?
> 
> https://github.com/noironetworks/aci-containers/blob/master/pkg/hostagent/services.go#L114

Sure Sumit, Let me add here too in this commit. Was going to ask about it whether we mention it in a separate commit just to record it as ingress change rather than flavor type commit.

**Review by snaiksat — APPROVED** [review]

**Pull request merged**
