### PR TITLE
Moving to OVS 2.10.1

### PR DESCRIPTION
**Pull request by snaiksat**
Using alpine 3.9 as base image

### CODE REVIEW

**Comment by mchalla** [comment]
I understand that ovs is backward and forward compatible when it comes to using any version of the kernel module with any version of ovs. I am not completely sure the same applies to ovs commands running against a certain version of ovs. (The recommendation is to recompile commands with that version) Since agent uses ovs headers similar to the commands I believe a similar concern exists for the agent. I am wondering what kind of testing we should be doing to qualify the upgrades since recompiling our code with newer headers is not straightforward. Thoughts ?

**Comment by mchalla** [comment]
Basically when we change agent, make check compares known set of flows against the changed set and fails if anything changes. We need something similar here, although we cannot unfortunately compile agent with newer headers. May be an alternative is to run a decent feature set with older version of ovs, get the flow dump and compare the same feature set against the newer version of ovs. Other than that its fine with me. I also feel we should look into upgrading agent to use the newer headers.

**Comment by snaiksat** [comment]
I believe the past approach has been to fix things if found broken. I understand that a similar approach was followed for moving to using OVS 2.9 for OpenStack. Adding @mandeepdhami to this review since the move to 2.10 was suggested by him.

**Comment by mchalla** [comment]
I guess it should be fine to merge it then.

**Pull request merged**
